apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-repo-scan
spec:
  params:
    - name: repo-url
      description: "The location of repo to scan"
      default: ""
    - name: TRIVY_IMAGE
      default: docker.io/aquasec/trivy
  steps:
    - name: scan-repo
      image: $(params.TRIVY_IMAGE)
      command: ["trivy"]
      args:
        - "repo"
        - "$(params.repo-url)"
